version: "3"
services:
  db:
    container_name: entrance-system-db
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - entrance-db:/var/lib/mysql
    networks:
      - entrance-system-network
  
volumes:
  entrance-db:

networks:
  entrance-system-network:
    driver: bridge